filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/brazil.log
  fields:
    application: brazil
  fields_under_root: true
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/japan.log
  fields:
    application: japan
  fields_under_root: true
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
